# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-08 13:31
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('creation_time', models.DateTimeField()),
                ('last_update', models.DateTimeField()),
                ('upload_code', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='DBConf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=512)),
                ('creation_time', models.DateTimeField()),
                ('configuration', models.TextField()),
                ('similar_conf', models.TextField(default=b'zbh')),
                ('db_type', models.CharField(max_length=9)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Application')),
            ],
        ),
        migrations.CreateModel(
            name='ExperimentConf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=512)),
                ('configuration', models.TextField()),
                ('benchmark_type', models.CharField(max_length=512)),
                ('creation_time', models.DateTimeField()),
                ('isolation', models.TextField()),
                ('scalefactor', models.TextField()),
                ('terminals', models.TextField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Application')),
            ],
        ),
        migrations.CreateModel(
            name='FEATURED_PARAMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_type', models.CharField(max_length=64)),
                ('params', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='LEARNING_PARAMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_type', models.CharField(max_length=64)),
                ('params', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('creation_time', models.DateTimeField()),
                ('last_update', models.DateTimeField()),
                ('upload_code', models.CharField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField()),
                ('timestamp', models.DateTimeField()),
                ('throughput', models.FloatField()),
                ('avg_latency', models.FloatField()),
                ('min_latency', models.FloatField()),
                ('p25_latency', models.FloatField()),
                ('p50_latency', models.FloatField()),
                ('p75_latency', models.FloatField()),
                ('p90_latency', models.FloatField()),
                ('p95_latency', models.FloatField()),
                ('p99_latency', models.FloatField()),
                ('max_latency', models.FloatField()),
                ('most_similar', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Application')),
                ('benchmark_conf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.ExperimentConf')),
                ('db_conf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.DBConf')),
            ],
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField()),
                ('throughput', models.FloatField()),
                ('avg_latency', models.FloatField()),
                ('min_latency', models.FloatField()),
                ('p25_latency', models.FloatField()),
                ('p50_latency', models.FloatField()),
                ('p75_latency', models.FloatField()),
                ('p90_latency', models.FloatField()),
                ('p95_latency', models.FloatField()),
                ('p99_latency', models.FloatField()),
                ('max_latency', models.FloatField()),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Result')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('creation_time', models.DateTimeField()),
                ('finish_time', models.DateTimeField(null=True)),
                ('running_time', models.IntegerField(null=True)),
                ('status', models.CharField(max_length=64)),
                ('traceback', models.TextField(null=True)),
                ('result', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Website_Conf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('value', models.CharField(max_length=512)),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Project'),
        ),
        migrations.AddField(
            model_name='application',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
