# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 17:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DBConf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=512)),
                ('creation_time', models.DateTimeField()),
                ('configuration', models.TextField()),
                ('db_type', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='ExperimentConf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=512)),
                ('configuration', models.TextField()),
                ('benchmark_type', models.CharField(max_length=118)),
                ('creation_time', models.DateTimeField()),
                ('isolation', models.TextField()),
                ('scalefactor', models.TextField()),
                ('terminals', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('creation_time', models.DateTimeField()),
                ('last_update', models.DateTimeField()),
                ('upload_code', models.CharField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('throughput', models.FloatField()),
                ('avg_latency', models.FloatField()),
                ('min_latency', models.FloatField()),
                ('p25_latency', models.FloatField()),
                ('p50_latency', models.FloatField()),
                ('p75_latency', models.FloatField()),
                ('p90_latency', models.FloatField()),
                ('p95_latency', models.FloatField()),
                ('p99_latency', models.FloatField()),
                ('max_latency', models.FloatField()),
                ('most_similar', models.CommaSeparatedIntegerField(max_length=100)),
                ('benchmark_conf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.ExperimentConf')),
                ('db_conf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.DBConf')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField()),
                ('throughput', models.FloatField()),
                ('avg_latency', models.FloatField()),
                ('min_latency', models.FloatField()),
                ('p25_latency', models.FloatField()),
                ('p50_latency', models.FloatField()),
                ('p75_latency', models.FloatField()),
                ('p90_latency', models.FloatField()),
                ('p95_latency', models.FloatField()),
                ('p99_latency', models.FloatField()),
                ('max_latency', models.FloatField()),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Result')),
            ],
        ),
        migrations.AddField(
            model_name='experimentconf',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Project'),
        ),
        migrations.AddField(
            model_name='dbconf',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Project'),
        ),
    ]
