# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-18 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbconf',
            name='similar_conf',
            field=models.TextField(default=b''),
        ),
    ]
