# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-04 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_dbconf_similar_conf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbconf',
            name='similar_conf',
            field=models.TextField(default=b'zbh'),
        ),
    ]
